# Generated by Django 3.1.13 on 2022-04-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsbag_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source_link',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_path',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
