# Generated by Django 3.2.14 on 2022-09-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsbag_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='entity',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='keyword',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='sentiment',
            field=models.TextField(null=True),
        ),
    ]
